// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20220617162017_bornData")]
    partial class bornData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("API.Models.Data", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("BornStastitics");
                });

            modelBuilder.Entity("API.Models.RegionData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountBornFemale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountBornMale")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("DataID");

                    b.ToTable("RegionData");
                });

            modelBuilder.Entity("API.Models.RegionData", b =>
                {
                    b.HasOne("API.Models.Data", null)
                        .WithMany("RegionData")
                        .HasForeignKey("DataID");
                });

            modelBuilder.Entity("API.Models.Data", b =>
                {
                    b.Navigation("RegionData");
                });
#pragma warning restore 612, 618
        }
    }
}
